[68] перевел авто-архивацию студентов в крон задачу
PriTexX/PhysEdJournal pull request #16
Opened 2023-10-31 15:04 UTC by BR7RKR

2023-10-31 17:00 UTC, PriTexX requested changes

2023-10-31 17:00 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +                ArgumentNullException.ThrowIfNull(students);
Зачем?

2023-10-31 17:00 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +            _logger.LogError(e, "Error: {EMessage}", e.Message);
Сообщение ошибки уже есть в самой ошибке, не нужно его логировать дважды. А вот гуид студента, у которого случилась ошибка был бы полезен в логах.

2023-10-31 17:00 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +        _logger.LogInformation("Архивация прошла успешно");
Бесполезный лог да еще и на русском. Сделай счетчик успешно заархивированных студентов и здесь выводи его вместе с сообщением о завершении и кол-вом студентов которых было необходимо заархивировать, а перед началом выполнения джобы залогируй факт начала.

2023-10-31 17:00 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +        }
Зачем?

2023-11-05 19:07 UTC, BR7RKR commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +                ArgumentNullException.ThrowIfNull(students);
На всяки

2023-11-05 19:08 UTC, BR7RKR commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +                ArgumentNullException.ThrowIfNull(students);
На всякий пожарный. Еще хотел молитву ебануть, но решил, что будет уже лишнее. Мб баг будет атеистом)

2023-11-05 19:13 UTC, BR7RKR commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +            _logger.LogError(e, "Error: {EMessage}", e.Message);
Я просто у тебя из логов взял. Ты похоже сделал в api где-то

2023-11-05 19:50 UTC, BR7RKR commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +        }
для баланса вселенной

2023-11-06 11:51 UTC, PriTexX requested changes
Перед началом джобы должен быть лог, о начале джобы
`Archiving job has started`
После идет блок try/catch, в котором вытаскиваются студенты и архивируются
Потом если try/catch упал в catch блок, то там лог
`Archiving job has finished with error` (и прокинуть ошибку)
Если все норм, то 
`Archiving job has finished with success. 14 out 20 students were archived`

2023-11-06 11:51 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +                return;
Из-за этого return будет такая ситуация в логах: 
`Arhicivng job has started`
а что джоба завершилась лога не будет, а он нужен, даже если никого не нужно архивировать в лог все равно надо записать, что джоба завершилась и заархивировала 0 из 0 студентов

2023-11-06 11:51 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +            succArchivedStudents
Этот лог лежит как-то оторвано от остальной логики, помести его в блок try. И добавь в лог еще кол-во студентов, которые должны были быть заархивированы. `Archiving job is over. 14 out of 20 students were archived`

2023-11-06 11:51 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +                    $"Failed to archive student with guid{archivePayload.StudentGuid}"
Здесь лучше проверять не success и потом continue, а проверять IsError и тогда кидать ошибку, так читается лучше. Плюс в самом логе не отображено почему он не смог заархивировать студента, а должна быть причина, да и сам эксепшен написан криво у тебя здесь получится что-то вроде `Failed to archive student with guidfghhi12gh4i124h1251` в итоге.  Да и логика здесь сделана не так, как нужно, с такой реализацией при ошибке архивации у одного студента, у тебя остановится архивация всех остальных, а такого быть не должно.

2023-11-06 11:51 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +                var result = await _command.ExecuteAsync(archivePayload);
Оберни вызов в try/catch, чтобы 1 студент не валил архивацию всех остальных. И когда проверяешь result, если там ошибка, то логируй её как Warning

2023-11-06 11:51 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +        var succArchivedStudents = 0;
Назови переменную `successfullyArchivedStudentsCounter` здесь можно пожертвовать краткостью ради ясности

2023-11-11 18:14 UTC, BR7RKR commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +                var result = await _command.ExecuteAsync(archivePayload);
вызов никогда ошибку не выкинет

2023-11-11 18:15 UTC, BR7RKR commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +                var result = await _command.ExecuteAsync(archivePayload);
Оно резалт возвращает. Внутри будет ошибка

2023-11-12 07:25 UTC, PriTexX requested changes

2023-11-12 07:25 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +            _logger.LogInformation("Archiving job has started");
Дублируются

2023-11-12 07:25 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +            }
Это вообще здесь не нужно. Если массив будет пустой, то foreach просто ничего не сделает и сразу вызовется лог после него, который выведет точно такое же сообщение

2023-11-12 07:25 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +                        archivePayload.StudentGuid
В логе нет самой ошибки, из-за которой не получилось заархивировать. У `LogWarning` есть перегрузка, которая 1 параметром принимает `exception`

2023-11-12 07:25 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +                var result = await _command.ExecuteAsync(archivePayload);
У тебя все равно 1 студент может свалить всех остальных, если при выполнении команды будет выброшен эксепшн. Оберни этот вызов в еще один `try/catch`

2023-11-12 07:25 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +                successfullyArchivedStudentsCounter++;
Смысл этой переменной, если она всегда увеличивается? Она должна увеличиваться, только если студента получилось заархивировать

2023-11-12 07:25 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +            _logger.LogError(e, "Archiving job has finished with error");
Придерживайся консистентности в логах, где это возможно. 
`"Archiving job has finished with success. {SuccArchivedStudents} out of {TotalStudents} students were archived"` 
Пиши здесь этот лог, т.к. даже если в какой-то момент джоба зафейлится, это не значит, что она не успела кого-то заархивировать

2023-11-12 07:30 UTC, PriTexX requested changes

2023-11-12 07:30 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Services/Quartz/Jobs/ArchiveStudentJob.cs
> +                "Archiving job has finished with success. {SuccArchivedStudents} out of {TotalStudents} students were archived",
Тут забыл поменять название параметра `SuccArchivedStudents` на нормальное

2023-11-13 21:09 UTC, PriTexX approved these changes

2023-11-13 21:19 UTC, merged