Добавил команду для взаимодействия с csv
PriTexX/PhysEdJournal pull request #17
Opened 2023-12-05 12:15 UTC by LoykoD

2023-12-05 12:29 UTC, PriTexX requested changes
Вместо того, чтобы итерировать по строкам файла(что кстати не работает у тебя) лучше сначала распарсить файл, распихать данные в массив структур (для этого создай прям в файле `file struct CsvTeacher{...}` в котором будут все нужные тебе данные с каждой строки) и уже потом итерируя по этому массиву структур менять бд. Плюс у тебя здесь не реализовано выставление стоимости посещений для групп

2023-12-05 12:29 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/SetCuratorsFromFile.cs
> +    public required string TeacherGuid { get; init; } // Список препод
Единственный входной параметр - PayloadFile. В нем и находится вся инфа о преподах, группах, баллах для каждой группы и какой препод куратором какой группы является

2023-12-05 12:29 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/SetCuratorsFromFile.cs
> +        var rowsAffected = await _applicationContext.Teachers.ToListAsync(); // Получаю список всех преподов
Почему переменная называется `rowsAffected` если в ней лежат `teachers`?

2023-12-05 12:29 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/SetCuratorsFromFile.cs
> +        var file = commandPayload.PayloadFile; // Получаю csv и прохожусь по нему
Можно было и не создавать отдельную переменную для этого

2023-12-05 12:29 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/SetCuratorsFromFile.cs
> +        for (var i = 0; i < file.Length; i++)
Можно использовать foreach, а не for

2023-12-05 12:29 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/SetCuratorsFromFile.cs
> +            }
Вместо того, чтобы каждый раз проверять строку на то, что она 1 можно просто начать итерировать со 2 строки

2023-12-05 12:29 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/SetCuratorsFromFile.cs
> +            double visitCost = double.Parse(rowData[2]); // Если первая строка с описанием столбцов, то скип
Что-то тут какой-то бред происходит. С чего вдруг 1 байт = целая строка

2023-12-05 12:29 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/SetCuratorsFromFile.cs
> +                var teacher = await _applicationContext.Teachers.FindAsync(fullName); // Достаю из БД препода и проверяю что он существует
А зачем было доставать всех учителей из бд, чтобы потом еще раз достать их из бд, только теперь по 1? И FindAsync ищет по первичному ключу, фио, это, конечно же, не первичный ключ

2023-12-05 12:29 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/SetCuratorsFromFile.cs
> +                }
Правильно сделал, что не стал `throw` ошибки, но здесь лучше вообще не откидываться ошибками, а залогировать предупреждение и продолжить к следующему учителю

2023-12-05 12:29 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/SetCuratorsFromFile.cs
> +                group.Curator = teacher; // Присваиваю кураторку
Это делать не нужно, ef core сам присвоит

2023-12-05 12:29 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/SetCuratorsFromFile.cs
> +                group.CuratorGuid = teacher.TeacherGuid;
В конце, чтобы изменения сохранились нужно вызвать `SaveChangesAsync` у ApplicationContext

2023-12-16 08:37 UTC, PriTexX requested changes
Убери мусор из коммита, все комменты и пофикси ошибки из-за которых проверки падают, чтобы пайплайн прошел, иначе будет нельзя вмерджитьь

2023-12-16 08:37 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/SetCuratorsFromFile.cs
> +    public required StreamReader PayloadFile { get; init; } // csv file
Давай здесь все-таки использовать более общий тип - `Stream`

2023-12-16 08:37 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/SetCuratorsFromFile.cs
> +            HasHeaderRecord = false,
А разве если здесь поставить `true`, то он не пропустит 1 строку автоматом? Проверь документацию, мне кажется что эта настройка именно для этого

2023-12-16 08:37 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/SetCuratorsFromFile.cs
> +                    Console.WriteLine($"Teacher {fullName} not found in database, group {numberGroup} was not assigned a curator");
Консоль врайт в продакшн коде? Используй логгер, примеры есть в других командах, вроде в команде архивации

2023-12-16 08:37 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/SetCuratorsFromFile.cs
> +                foreach (var teacher in teachersList) // Прохожусь по списку учителей
Чтобы не изобретать велосипед используй методы расширения LINQ на коллекциях. В данном случае, чтобы найти элемент, которого возможно нет, в коллекции есть `FirstOrDefault`

2023-12-24 14:18 UTC, LoykoD commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/SetCuratorsFromFile.cs
> +            HasHeaderRecord = false,
Если значение установлено в false, то предполагается, что CSV-файл не имеет заголовка, и данные начинаются сразу со второй строки.

2023-12-26 20:20 UTC, closed without merging