Feature/update students info rework
PriTexX/PhysEdJournal pull request #18
Opened 2023-12-16 09:49 UTC by D1098

Попытка переписать команду **UpdateStudentsInfoCommand**

https://github.com/PriTexX/PhysEdJournal/tree/main/PhysEdJournal.Infrastructure/Commands/AdminCommands/UpdateStudentsInfoCommand.cs

2023-12-16 12:22 UTC, PriTexX requested changes

2023-12-16 12:22 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/UpdateStudentsInfoCommand.cs
> +                .ToList();
Лучше отфильтровать всех не нужных студентов еще на этапе получения студентов в 36 строчке, чтобы в `allStudents` лежали уже только нужные

2023-12-16 12:22 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/UpdateStudentsInfoCommand.cs
> +                    .FindAsync(student.Guid);
Не думаю, что 16 тысяч запросов к бд это хорошая идея. Вытяни сначала всех студентов, которые тебе нужны будут. Можешь это сделать по группе.

2023-12-16 12:22 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/UpdateStudentsInfoCommand.cs
> +            await UpdateGroups(applicationContext, filteredStudents);
Вынеси команду из цикла вверх. Чтобы сначала добавлялись все нужные группы, а только потом уже обновлялись студенты

2023-12-16 12:22 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/UpdateStudentsInfoCommand.cs
> +    private static partial Regex MyRegex();
Давай без regex. Он тут никакой пользы не дает кроме излишнего усложнения. Достаточно функцию фильтрации, которая отфильтрует ненужные группы. И туда еще добавить проверка на `g => !string.IsNullOrEmpty(g)`. А то сейчас у тебя в `UpdateGroups` фильтр стоит на пустые строки, которых там нет, т.к. ты выше отфильтровал уже

2023-12-16 12:22 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/UpdateStudentsInfoCommand.cs
> +                var updatedEntity = GetUpdatedOrCreatedStudentEntities(student, dbStudent, currentSemesterName);
Посмотри что можно еще сделать с `GetUpdatedOrCreatedStudentEntities` его тоже по-хорошему нужно отрефачить. Да и как минимум перенести сюда, чтобы все было в 1 месте, а не раскидано

2023-12-16 12:23 UTC, PriTexX requested changes
Подтяни еще с дева изменения, а то у тебя там конфликт какой-то

2023-12-20 18:21 UTC, PriTexX requested changes

2023-12-20 18:21 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/UpdateStudentsInfoCommand.cs
> +                >= '0' and <= '9'
Шо то здесь не то, что было. Этот фильтр нужен, чтобы убрать студентов групп, у которых уже нет физры. Тоесть всякие магистранты и 4 курс. Здесь же вообще все группы у тебя стоят и по сути фильтрует только пустые группы

2023-12-20 18:21 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/UpdateStudentsInfoCommand.cs
> +            await allStudents.ToListAsync(); // Придется сделать так чтобы UpdateGroups мог отработать до цикла
А зачем вынес это все в отдельную переменную, если можно было сразу после `Where(...).ToListAsync()` сделать

2023-12-20 18:21 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/UpdateStudentsInfoCommand.cs
> +        var allStudents = GetAllStudentsAsync(_userInfoServerUrl, pageSize: _pageSize)
Вообще все функции из StudentService нужно сюда перенести и удалить тот файл

2023-12-20 18:21 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/UpdateStudentsInfoCommand.cs
> +                .Where(group => !string.IsNullOrEmpty(group))
Ты уже фильтровал на пустые группы

2023-12-20 18:21 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/UpdateStudentsInfoCommand.cs
> +                    dbStudent.Group != null && distinctFilteredGroups.Contains(dbStudent.Group.GroupName))
Зачем проверка на dbStudent.Group? У студента не может не быть группы, да и проверка эта в рамках бд не имеет никакого смысла, т.к. в бд нет никакой `Group` это навигационное свойство ef core

2023-12-20 18:21 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/UpdateStudentsInfoCommand.cs
> +            }
Это можно переписать через LINQ. 
Например
`var updatedEntities = filteredStudents.Select(s => {
    var dbStudent = ...;
    return GetUpdatedOrCreated(...);
})`

2023-12-20 18:51 UTC, D1098 commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/UpdateStudentsInfoCommand.cs
> +                >= '0' and <= '9'
Изначально была задача отфильтровать по паттерну 2*[1,9]-***, сделал соответствующий (по крайней мере как мне казалось) regex, сейчас поменял этот regex на другой фильтр просто. Я либо совсем не то делал изначально, либо с паттерном что-то не так

2023-12-20 18:56 UTC, D1098 commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/UpdateStudentsInfoCommand.cs
> +            await allStudents.ToListAsync(); // Придется сделать так чтобы UpdateGroups мог отработать до цикла
Там далее в цикле используется allStudents.Buffer() , поэтому решил так

2023-12-20 18:58 UTC, D1098 commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/UpdateStudentsInfoCommand.cs
> +            await allStudents.ToListAsync(); // Придется сделать так чтобы UpdateGroups мог отработать до цикла
Могу только убрать allStudentsList как переменную и передавать напрямую await allStudents.ToListAsync() в UpdateGroups

2023-12-20 19:03 UTC, D1098 commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/UpdateStudentsInfoCommand.cs
> +            }
```
var updatedEntities =
                (from student in filteredStudents
                    let dbStudent = dbStudents.FirstOrDefault(db => db.StudentGuid == student.Guid)
                    select GetUpdatedOrCreatedStudentEntities(student, dbStudent, currentSemesterName)).ToList();
```

Я решил так не делать чтобы было проще читать, но ок

2023-12-20 19:12 UTC, PriTexX requested changes

2023-12-20 19:12 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/UpdateStudentsInfoCommand.cs
> +                >= '0' and <= '9'
Изначально делал не то получается. `.Where(p => p.Item2.GroupNumber[2] == '1' || p.Item2.GroupNumber[2] == '9')` такой фильтр там стоял

2023-12-20 19:12 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/UpdateStudentsInfoCommand.cs
> +            await allStudents.ToListAsync(); // Придется сделать так чтобы UpdateGroups мог отработать до цикла
А, тогда это вообще пиздец. Ты 2 раза запрашиваешь всех студентов зачем-то. Первый раз когда получаешь allStudentsList, а второй раз ты идешь в сервис за теми же самыми данными повторно, когда пробегаешься в await foreach. `Buffer` есть и на `List` так что не знаю почему сразу не кастанул в него

2023-12-20 19:12 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/UpdateStudentsInfoCommand.cs
> +            }
Так и не делай так хуево то... Зачем этот синтаксис который никто не использует? Я же тебе почти весь примерно написал как надо `...` только на соответствующий код замени

2024-04-09 20:23 UTC, closed without merging