Removing semester bound
PriTexX/PhysEdJournal pull request #20
Opened 2023-12-26 13:44 UTC by BR7RKR

Убрал привязку к семестрам и добавил сохранение лишней истории у должника при архивации во время покрытия долга

2023-12-26 20:54 UTC, PriTexX commented on PhysEdJournal.Core/Entities/DB/ArchivedStudent.entity.cs
> +    public ICollection<StandardsStudentHistoryEntity>? StandardsStudentHistory { get; set; }
[ColumnType("json")] забыл добавить к ним, без этого он тупо создаст новые таблички. И убери `nullable` если у студента нет чего-то, то просто пустой массив будет

2023-12-26 20:54 UTC, PriTexX commented on PhysEdJournal.Core/Entities/DB/PointsStudentHistory.entity.cs
> +    public bool ShouldBeArchived { get; set; } = true;
Чет это фигня какая-то в модель пихать доп. свойства, чтобы в 1 месте их использовать

2023-12-26 20:54 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +                        s.VisitsStudentHistory,
Вместо `Select` вытягивай всего студента вместе с историями через `Include`

2023-12-26 20:54 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +        }
Не понятно почему эта проверка здесь, а не выше

2023-12-26 20:54 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +    )
Такое здесь не нужно, метод который меняет состояние сущностей и потом отдает их вообще очень плохая идея, тем более что здесь он вообще не нужен

2023-12-26 20:54 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +    private class SuperHistoryEntity
Еще есть ключевое слово `file` которое делает класс видимым только в текущем файле, да и лучше это сделать `struct` т.к. класс здесь вообще не нужен

2023-12-26 20:54 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +            if (r.HistoryType != nameof(VisitStudentHistoryEntity))
Давай для типов историй лучше сделаем `enum`

2023-12-26 20:54 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Services/StudentArchiver.cs
>          await ArchiveCurrentSemesterHistoryAsync(student.StudentGuid, student.CurrentSemesterName);
Этот метод переводил истории в следующий семестр, сейчас этого нет, тогда почему он остался? И ты не удалил свойство `IsArchived` у историй

2023-12-26 20:54 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Services/StudentArchiver.cs
> +        }
Вместо того, чтобы удалять, а потом добавлять одно  и то же, можно просто удалить не нужное

2024-01-03 13:25 UTC, PriTexX requested changes

2024-01-03 13:25 UTC, PriTexX commented on PhysEdJournal.Core/Entities/DB/ArchivedStudent.entity.cs
> +    public ICollection<VisitStudentHistoryEntity>? VisitStudentHistory { get; set; }
а чего оно наллабл?

2024-01-03 13:25 UTC, PriTexX commented on PhysEdJournal.Core/Entities/Types/HistoryType.cs
> +}
Это внутренний вспомогательный класс для команды архивации он не должен быть тут

2024-01-03 13:25 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +        }
Почему здесь кидается какая-то осмысленная ошибка? Тут не может быть группа наллом. Если компилятор ругается на наллабл значение можно проверить его через `ArgumentNullException.ThrowIfNull`

2024-01-03 13:25 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +            standardsToArchive = new List<StandardsStudentHistoryEntity>();
Можно сделать так:
```suggestion
            visitsToArchive = studentFromDb.VisitsHistory.Filter(h => histories.Include(h.Id));
            pointsToArchive = studentFromDb.PointsHistory.Filter(h => histories.Include(h.Id));
            standardsToArchive = studentFromDb.StandardsHistory.Filter(h => histories.Include(h.Id));
```
Так получается и тип даже не нужен в этом массиве

2024-01-03 13:25 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +        var standardsToArchive = studentFromDb.StandardsStudentHistory;
Давай так не делать. Сейчас это работает неявно: ты создаешь 3 переменных историй, которые ссылаются на исходные массивы и потом удаляешь из исходных истории. Это смерть для дебага в будущем

2024-01-03 13:25 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +    }
А это что должно делать? Зачем оно удаляет одну случайную историю? Да и название вообще не понятное

2024-01-03 13:25 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +            throw new Exception("Has total points with no history");
Поменяй сообщение ошибки, не понятно причем здесь тотал поинтс и эта часть кода

2024-01-03 13:25 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +        } while (sum < REQUIRED_POINT_AMOUNT);
Это можно переписать через обычный `foreach` по отсортированному allHistory

2024-01-03 13:25 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +        await _applicationContext.SaveChangesAsync();
Вот этот вызов saveChangesAsync портит всю транзакционность. Такие вызовы к бд должны совершаться самим вызывающим кодом в конце метода, а не вспомогательным методом

2024-01-03 13:25 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Models/InternalArchiveStudentPayload.cs
>  internal sealed class InternalArchiveStudentPayload
Давай эту штуку тоже в команду архивации засунем, а то это чет странное

2024-01-04 17:48 UTC, BR7RKR commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +            standardsToArchive = new List<StandardsStudentHistoryEntity>();
сомнительно

2024-01-04 17:49 UTC, BR7RKR commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +    }
Оно удаляет все истории одного человека. Проебался с first.

2024-01-06 11:45 UTC, PriTexX requested changes

2024-01-06 11:45 UTC, PriTexX commented on PhysEdJournal.Core/Entities/DB/ArchivedStudent.entity.cs
> +        new List<StandardsStudentHistoryEntity>();
не надо в модели что-то скрытно инициировать. Пометь их required и сделай тип List<...>

2024-01-06 11:45 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> -        }
Давай пока оставим это. Т.к. сейчас если не создали новый сем, то будет какаха

2024-01-06 11:45 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +        studentFromDb.PointsStudentHistory ??= new List<PointsStudentHistoryEntity>();
Странный мув, так лучше не делать, не понятно зачем ты инициализируешь пустые массивы у студента. Либо перемести поближе к тому коду, где это используется

2024-01-06 11:45 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +    private struct SuperHistoryEntity
Давай просто `HistoryEntity`

2024-01-06 11:45 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +        await _applicationContext.ArchivedStudents.AddAsync(archivedStudent);
Убери асинк версию и используй просто `Add`

2024-01-06 11:45 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
>          );
Этот метод считает баллы студента с учетом стоимости посещения в группе, но если чел должник, то считать надо его стоимость посещения, а не группы

2024-01-06 11:45 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +    private IEnumerable<SuperHistoryEntity> FindHistoriesToArchive(
Ты возвращаешь List, а не IEnumerable. А в том месте, где ты принимаешь этот лист ты еще раз вызываешь `ToList`. Сделай уже здесь возвращаемый тип листом сразу

2024-01-06 11:45 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +            )
Тут напутано всё. Истории нужно искать только если чел должник, а ты ищешь всегда. Получается если студент без долгов, то у него перейдут некоторые баллы в новый сем. Чтобы не менять сильно код, можешь передавать в метод FindHistories бул флаг должник ли. Если не должник, то он отдает все истории на архивацию

2024-01-06 11:45 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +        }
А тут что происходит? Почему проверка на > 50? Тут почти всегда будет больше 50 т.к. если < 50, то отдает ошибку NotEnoughPoints

2024-01-06 11:45 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +            studentFromDb.StandardsStudentHistory?.Sum(h => h.Points) ?? 0;
Убери все `?` ты же их выше проинициализировал. Либо убери инициализацию, что будет лучше и оставь здесь `?`

2024-01-06 11:45 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +        studentFromDb.AdditionalPoints = 0;
тут пропустил что-то

2024-01-06 11:45 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +    }
Можешь здесь сделать source наллабл, чтобы не инициализировать пустыми массивами напрямую в студенте

2024-01-06 11:45 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +        StandardsHistory,
Можно убрать везде `History` в конце, и так из названия понятно, что это тип истории. и заменить `Points` на `AdditionalPoints`

2024-01-06 11:45 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +        public required bool HasDebt { get; init; }
А это поле зачем?

2024-01-06 11:45 UTC, PriTexX commented on PhysEdJournal.Infrastructure/Commands/AdminCommands/ArchiveStudentCommand.cs
> +        public required ICollection<PointsStudentHistoryEntity> PointsStudentHistory { get; init; }
Тут тоже сделай `List`ом

2024-01-13 11:43 UTC, PriTexX approved these changes

2024-01-13 11:43 UTC, merged