fix: health group providing rework
PriTexX/PhysEdJournal pull request #44
Opened 2024-09-20 15:58 UTC by etogood

2024-09-20 19:07 UTC, PriTexX requested changes
В проекте используется `csharpier` для валидации качества кода  - можешь глянуть подробнее [тут](https://csharpier.com/docs/Editors) настройку для своей ide или запускать его через консоль командой `dotnet csharpier .`

2024-09-20 19:07 UTC, PriTexX commented on Api/Rest/Student/Contracts/GetStudent.cs
> +    public TeacherEntity? HealthGroupProvider { get; set; }
Сейчас получается, что в контракте апи находится модель уровня базы данных, так лучше не делать по нескольким причинам:

1. Модель бд может меняться и эти изменения не обязательно должны отражаться в контракте апи
2. На фронт передаются лишние данные (Фактически вся таблица `TeacherEntity` таким образом попадает на фронт, хотя там нужен только гуид и fullName)
3. В Asp.net и ef core есть такая штука как кросс-референсы (Это когда модели бд ef core содержат внутри себя пересекающиеся ссылки друг на друга или навигационные свойства). Если в модели они окажутся, то такой ответ просто будет всегда 500 отдавать, т.к. asp.net не сможет его сериализовать без доп. настройки

Создай отдельный класс прям в этом файле `TeacherResponse` и запиши туда эти данные, а потом в контроллере  просто мапь в него

2024-09-20 19:07 UTC, PriTexX commented on Core/Commands/AddHealthGroup/AddHealthGroup.cs
> +file sealed class AddHealthGroupValidator(ApplicationContext appContext) : ICommandValidator<AddHealthGroupPayload>
Лучше не использовать primary конструкторы, это все-таки не то же самое, что и обычное поле, т.к. они не `readonly`, да и пользы от них особо нет.

Если все-таки хочется использовать их, то стоит это делать везде для консистентности, а то сейчас получается, что он используется только в 1 файле

2024-09-20 19:07 UTC, PriTexX commented on Core/Commands/AddHealthGroup/AddHealthGroup.cs
>      }
А нужен ли вообще такой валидатор, который проверяет, что учитель существует?

Смысл валидаторов в проверке бизнес правил приложения - существование учителя таковым не является и это не забота команды проверять существует ли он вообще по нескольким причинам:

1. Проверку существования учителя проверяет мидлваря авторизации, если учителя нет, то сюда запрос не дойдет и вернет 401
2. Учителя у нас из бд не удаляются вообще, поэтому даже с кэшами такой ситуации возникнуть не может
3. На уровне бд стоит ограничение внешнего ключа, поэтому даже если как-то обойти мидлварю авторизации и удалить препода, то внешний ключ все равно не даст сохранить такую запись и выкинет ошибку

Тут стоит вообще убрать валидатор, т.к. нечего валидировать больше

2024-09-20 19:07 UTC, PriTexX commented on Core/Commands/AddHealthGroup/AddHealthGroup.cs
> +        student.HealthGroupProvider = await appContext.Teachers.FindAsync(commandPayload.TeacherGuid);
Тут в целом можно оставить и так, но я бы лучше использовал вместо `FindAsync` - `FirstAsync`.
Это даст дополнительную уверенность в том, что команда работает правильно, т.к. мы будем точно знать, что в бд есть ровно 1 учитель, а не 0 или 1

2024-09-20 19:07 UTC, PriTexX commented on DB/Migrations/20240920152807_health-group-rework.cs
> +namespace DB.Migrations
У нас в проекте используется `csharpier` для проверки качества кода и на такие сгенерированные файлы он ругается, чтобы этого не происходило в самом верху нужно добавлять строку `// <auto-generated />` и желательно называть миграции в виде - `health_group_rework`

2024-09-20 19:07 UTC, PriTexX commented on DB/Tables/Student.cs
> +    public TeacherEntity? HealthGroupProvider { get; set; }
Лучше тут явно указать свойство внешнего ключа, можешь посмотреть на примере других отношений как оно указывается. Дополнительный контроль над бд может быть полезен, а каких-то сложностей это не создаст.

И лучше все-таки выбрать более понятное название, а то `provider` слабо говорит о назначении колонки (Я, например, повтыкал немного, пока не понял про что это)

Тут конечно достаточно сложно придумать что-то адекватное и полностью понятное, но могу предложить как вариант - `HealthGroupTeacher` (Та еще залупа если честно тоже)

2024-09-20 22:27 UTC, etogood commented on Core/Commands/AddHealthGroup/AddHealthGroup.cs
> +        student.HealthGroupProvider = await appContext.Teachers.FindAsync(commandPayload.TeacherGuid);
Изначально так и реализовал, но затем увидел, что выше, таким же образом ищется студент и решил написать так же для консистентности

2024-09-21 06:11 UTC, PriTexX commented on Core/Commands/AddHealthGroup/AddHealthGroup.cs
> +        student.HealthGroupProvider = await appContext.Teachers.FindAsync(commandPayload.TeacherGuid);
Пон, ну со студентом тут немного другая ситуация, его может и не быть в бд, т.к. указать несуществующий ид студента можно без проблем и в таком случае отдавать 500 не очень правильно, а вот преподаватель обязан быть в бд, т.к. есть мидлваря авторизации, которая не пускает несуществующих преподов

2024-11-03 22:47 UTC, closed without merging